In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/test-file/tested.csv

In [6]:
df=pd.read_csv("/kaggle/input/test-file/tested.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

We perform Chi-square test on categorical variables.
Let's perform chi2 test on two categorical variables in titanic data set.Survived and Pclass.

H0 is No significant association between Survived and Pclass.

Ha is there is a significant association between Survived and Pclass.

In [5]:
from scipy.stats import chi2_contingency #To perfom Chi2-test

In [8]:
contigency_table=pd.crosstab(df['Survived'],df['Pclass'])

In [9]:
chi2,p,df,expected=chi2_contingency(contigency_table)

In [10]:
print(p)

0.03519206276590605

In [11]:
if p<0.05:
    print(p,"Reject Null Hypothesis,There is a significant association between Survived and Pclass.")
else:
    print(p,"Accept Null Hypothesis,There is no significant association between Survived and Pclass.")

0.03519206276590605 Reject Null Hypothesis,There is a significant association between Survived and Pclass.